name: React Build & Deploy To S3

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Node.js 설치
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3) 의존성 설치
      - name: Install dependencies
        working-directory: saladMan-frontend
        run: npm install

     # 4) 환경변수 파일(.env) 생성 / 추가
      - name: Generate .env file
        working-directory: saladMan-frontend
        run: |
          echo "VITE_FIREBASE_APIKEY=${{ secrets.VITE_FIREBASE_APIKEY }}" >> .env
          echo "VITE_FIREBASE_VAPIKEY=${{ secrets.VITE_FIREBASE_VAPIKEY }}" >> .env
          echo "VITE_TOSS_CLIENT_KEY=${{ secrets.VITE_TOSS_CLIENT_KEY }}" >> .env 

      # 5) 빌드 실행
      - name: Build project
        working-directory: saladMan-frontend
        run: npm run build

      # 6) 빌드 결과 확인 (디버깅용)
      - name: Check build output
        working-directory: saladMan-frontend
        run: ls -l dist

      # 7) AWS 자격증명 설정
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # 8) S3 기존 파일 삭제 및 새 빌드 업로드
      - name: Sync build to S3 bucket
        run: |
          aws s3 rm --recursive s3://saladman-web
          aws s3 cp ./saladMan-frontend/dist s3://saladman-web/ --recursive

      # 9) CloudFront 캐시 무효화
      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id E3P9MO1X33X9JJ --paths "/*"

      # 10) 빌드 성공 Slack 알림
      - name: 빌드 성공 Slack 알림
        if: success()  # 빌드 성공 시에만 실행
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": ":white_check_mark: *빌드 성공!* `${{ github.workflow }}`\n브랜치: `${{ github.ref_name }}`\n커밋: `${{ github.sha }}`\n작성자: `${{ github.actor }}`"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      # 11) 배포 성공 Slack 알림
      - name: 배포 성공 Slack 알림
        if: success()
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": ":rocket: *배포 성공!* `${{ github.workflow }}`\n브랜치: `${{ github.ref_name }}`\n커밋: `${{ github.sha }}`\n작성자: `${{ github.actor }}`"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      # 12) 실패 시 Slack 알림
      - name: 실패 Slack 알림
        if: failure()
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": ":x: *실패!* `${{ github.workflow }}`\n브랜치: `${{ github.ref_name }}`\n커밋: `${{ github.sha }}`\n작성자: `${{ github.actor }}`"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
