name: React Build & Deploy To S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) 코드 체크아웃
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      # 2) Node.js 설치
      - name: Node.js 설치
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3) 의존성 설치 (working-directory 지정)
      - name: 의존성 설치
        working-directory: SaladMan_front
        run: npm install

      # 4) React 빌드 (working-directory 지정)
      - name: React 빌드
        working-directory: SaladMan_front
        run: npm run build

      # 5) AWS 자격증명 설정
      - name: AWS Resource에 접근할 수 있게 AWS credentials 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # 6) S3 기존 파일 전체 삭제 후 빌드 결과 업로드
      - name: S3 기존 파일들 전체 삭제 후 새로 업로드
        run: |
          aws s3 rm --recursive s3://saladman-web
          aws s3 cp ./SaladMan_front/build s3://saladman-web/ --recursive

      # 7) CloudFront 캐시 무효화
      - name: CloudFront 캐시 무효화
        run: aws cloudfront create-invalidation --distribution-id E3P9MO1X33X9JJ --paths "/*"

      # 8) 작업 디렉터리 내용 확인 (디버깅용)
      - name: 작업 디렉터리 내용 확인
        run: ls -R
